return {}
-- return {
--   {
--     'folke/noice.nvim',
--     event = 'VeryLazy',
--     opts = {
--       lsp = {
--         override = {
--           ['vim.lsp.util.convert_input_to_markdown_lines'] = true,
--           ['vim.lsp.util.stylize_markdown'] = true,
--           ['cmp.entry.get_documentation'] = true,
--         },
--       },
--       popupmenu = {
--         enabled = true,
--         backend = 'nui',
--       },
--     },
--     -- you can enable a preset for easier configuration
--     presets = {
--       command_palette = true, -- position the cmdline and popupmenu together
--       long_message_to_split = true, -- long messages will be sent to a split
--       inc_rename = true, -- enables an input dialog for inc-rename.nvim
--     },
--     cmdline_popup = {
--       position = {
--         row = 5,
--         col = '50%',
--       },
--       size = {
--         width = 60,
--         height = 'auto',
--       },
--     },
--     popupmenu = {
--       enabled = true, -- enables the Noice popupmenu UI
--       backend = 'cmp', -- backend to use to show regular cmdline completions
--       relative = 'editor',
--       position = {
--         row = 8,
--         col = '50%',
--       },
--       size = {
--         width = 60,
--         height = 10,
--       },
--       border = {
--         style = 'rounded',
--         padding = { 0, 1 },
--       },
--       win_options = {
--         winhighlight = { Normal = 'Normal', FloatBorder = 'DiagnosticInfo' },
--       },
--     },
--     dependencies = {
--       'MunifTanjim/nui.nvim',
--     },
--     routes = {
--       {
--         filter = {
--           event = 'msg_show',
--           any = {
--             { find = '%d+L, %d+B' },
--             { find = '; after #%d+' },
--             { find = '; before #%d+' },
--           },
--         },
--         view = 'mini',
--       },
--     },
--   },
-- }
